### ISSUE TITLE
mdt-list-devices fails with clCreateContext failed: INVALID_DEVICE

### ISSUE THREAD

**Issue by kcgthb** [cbclab/MDT#5]
Hi!

Using MDT 0.10.7, I can't seem to get the OpenCL context creation work.

`mdt-list-devices` fails with the following stack:
```
$ mdt-list-devices
Traceback (most recent call last):
  File "/share/software/user/open/py-mdt/0.10.7_py36/bin/mdt-list-devices", line 11, in <module>
    sys.exit(ListDevices.console_script())
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mdt/shell_utils.py", line 44, in console_script
    cls().start(sys.argv[1:])
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mdt/shell_utils.py", line 63, in start
    self.run(args, {})
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mdt/cli_scripts/mdt_list_devices.py", line 28, in run
    for ind, env in enumerate(cl_environments.CLEnvironmentFactory.smart_device_selection()):
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 255, in smart_device_selection
    cl_environments = CLEnvironmentFactory.all_devices()
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 235, in all_devices
    env = CLEnvironment(platform, device)
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 23, in __init__
    self._cl_context = CLRunContext(self)
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 151, in __init__
    self.context = cl.Context([cl_environment.device])
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
```

This is with CUDA 9.1 and a Tesla P100 GPU:
```
$ nvidia-smi -L
GPU 0: Tesla P100-SXM2-16GB (UUID: GPU-[...])
```

OpenCL programs work properly in the same context, including the [PyOpenCL benchmark](https://github.com/inducer/pyopencl/blob/master/examples/benchmark.py):
```
$ python3 benchmark.py
Execution time of test without OpenCL:  0.10260295867919922 s
===============================================================
Platform name: NVIDIA CUDA
Platform profile: FULL_PROFILE
Platform vendor: NVIDIA Corporation
Platform version: OpenCL 1.2 CUDA 9.1.84
---------------------------------------------------------------
Device name: Tesla P100-SXM2-16GB
Device type: GPU
Device memory:  16280 MB
Device max clock speed: 1480 MHz
Device compute units: 56
Device max work group size: 1024
Device max work item sizes: [1024, 1024, 64]
Data points: 8388608
Workers: 256
Preferred work group size multiple: 32
Execution time of test: 0.000208416 s
Results OK
```

Do you have any idea what the problem may be?

Thanks!

**Comment by robbert-harms** [comment]
Hi Kilian,

The error seems to me to be an OpenCL issue rather than MDT/MOT, since the error is thrown in the PyOpenCL library: ``pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE``. These errors are typically the result of building PyOpenCL using OpenCL 2.0 headers and using it with version 1.2 runtimes, like the NVIDIA's.

Strangely enough, the python3 python benchmark seems to run just fine. Could you perhaps launch a python3 shell and try the following:
``import pyopencl as cl``
``cl.get_platforms()``

This should ideally print a list of the platforms supported. If this crashes we know that the error is in the OpenCL library. If this works, the next would be to try:

``import mdt``
``mdt.get_cl_devices()``

This should also print the platforms. Things would get interesting if the latter fails while the first works.

Do let me know,

Robbert

**Comment by kcgthb** [comment]
Hi Robbert, 

I haven't looked at the code extensively, but it seems that the `smart_device_selection()` function in `mot/cl_environments.py` may not be returning a proper environment to initialize the CL context.

The OpenCL part seems to work and properly lists the available devices:
```
$ python3
Python 3.6.1 (default, Apr 27 2017, 10:57:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>> cl.get_platforms()
[<pyopencl.Platform 'NVIDIA CUDA' at 0x1dc6060>]
>>>
```

But the MDT part fails with this:
```
>>> mdt.get_cl_devices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mdt/utils.py", line 1213, in get_cl_devices
    return CLEnvironmentFactory.smart_device_selection()
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 255, in smart_device_selection
    cl_environments = CLEnvironmentFactory.all_devices()
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 235, in all_devices
    env = CLEnvironment(platform, device)
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 23, in __init__
    self._cl_context = CLRunContext(self)
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 151, in __init__
    self.context = cl.Context([cl_environment.device])
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
>>>
```

Thanks for looking into this!

**Comment by robbert-harms** [comment]
Hi Kilian,

Of course I will help and I am grateful for the bug report, as such I at least know what to fix.

I haven't encountered this problem before, but it probably is related to the order in which I initialize the OpenCL environment. Could you try running the following Python code and check if that works?

```
import pyopencl as cl
platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
context = cl.Context([device])
```

Best,

Robbert

**Comment by kcgthb** [comment]
Certainly, and I appreciate the support!

Here it it, that part works without returning any error:
```
$ python3
Python 3.6.1 (default, Apr 27 2017, 10:57:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> context = cl.Context([device])
>>>
>>> print(context)
<pyopencl.Context at 0x2368470 on <pyopencl.Device 'Tesla P100-SXM2-16GB' on 'NVIDIA CUDA' at 0x272dac0>>
>>> print(device)
<pyopencl.Device 'Tesla P100-SXM2-16GB' on 'NVIDIA CUDA' at 0x272dac0>
>>> print(platform)
<pyopencl.Platform 'NVIDIA CUDA' at 0x27a0090>
>>>
```

**Comment by robbert-harms** [comment]
and how about this:

```
import pyopencl as cl
from mot.cl_environments import CLEnvironment

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]

env = CLEnvironment(platform, device)

print(env)
```

I am sorry to have to steal your time for this, I can't seem to repeat it on my machines (Linux / Windows, AMD / NVIDIA).

**Comment by kcgthb** [comment]
No worries, happy to contribute if I can!

We're getting closer:
```
>>> import pyopencl as cl
>>> from mot.cl_environments import CLEnvironment
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>>
>>> env = CLEnvironment(platform, device)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 23, in __init__
    self._cl_context = CLRunContext(self)
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 151, in __init__
    self.context = cl.Context([cl_environment.device])
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
```

**Comment by robbert-harms** [comment]
We are getting closer indeed and it gets more interesting. There seems to be an issue with references, for some reason the stored device reference in the CLEnvironment seems to be getting invalid. Could you try this code again?

```
import pyopencl as cl

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]


class MockEnvironment(object):

    def __init__(self, platform, device):
        self._platform = platform
        self._device = device

    @property
    def platform(self):
        return self._platform

    @property
    def device(self):
        return self._device


class MockContext(object):

    def __init__(self, cl_environment):
        """Context for single run use

        Arguments:
            cl_environment (CLEnvironment): The environment for which to create a context and queue.
        """
        self.context = cl.Context([cl_environment.device])
        self.queue = cl.CommandQueue(self.context, device=cl_environment.device)


context = MockContext(MockEnvironment(platform, device))
```

I removed all MDT / MOT imports for eliminating possible side-effects.

**Comment by kcgthb** [comment]
Here you go:

```
>>> import pyopencl as cl
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>>
>>> class MockEnvironment(object):
...     def __init__(self, platform, device):
...         self._platform = platform
...         self._device = device
...     @property
...     def platform(self):
...         return self._platform
...     @property
...     def device(self):
...         return self._device
...
>>> class MockContext(object):
...     def __init__(self, cl_environment):
...         """Context for single run use
...         Arguments:
...             cl_environment (CLEnvironment): The environment for which to create a context and queue.
...         """
...         self.context = cl.Context([cl_environment.device])
...         self.queue = cl.CommandQueue(self.context, device=cl_environment.device)
...
>>> context = MockContext(MockEnvironment(platform, device))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in __init__
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.7_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE

**Comment by robbert-harms** [comment]
Great! Hopefully final one:

```
import pyopencl as cl

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]


class MockEnvironment(object):

    def __init__(self, platform, device):
        self._platform = platform
        self._device = device
        self._context = cl.Context([self._device])

context = MockEnvironment(platform, device)
```

**Comment by kcgthb** [comment]
That one works!
```
$ python3
Python 3.6.1 (default, Apr 27 2017, 10:57:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> class MockEnvironment(object):
...     def __init__(self, platform, device):
...         self._platform = platform
...         self._device = device
...         self._context = cl.Context([self._device])
...
>>> context = MockEnvironment(platform, device)
>>>
```

**Comment by robbert-harms** [comment]
Great! I think I can fix the issue then, it seems to be a problem with references to the devices. Apparently passing around the device / platform reference to much seems to be an issue. 

I'll change the code to circumvent this issue. That will probably be tomorrow. 

Perhaps one final test:

```
import pyopencl as cl

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]


class MockEnvironment(object):

    def __init__(self, platform, device):
        self.platform = platform
        self.device = device
        
environment = MockEnvironment(platform, device)
context = cl.Context([environment.device])
```

**Comment by robbert-harms** [comment]
Alright, thanks for the help! I'll let you know when the new version is out.

**Comment by robbert-harms** [comment]
I just pushed a new version of MOT (the computation library of MDT) which should fix this issue. Could you try updating to MOT v0.3.11 and see if that works for you?

**Comment by kcgthb** [comment]
Hi Robbert,

I just updated, but unfortunately, that doesn't seem to fix the issue:
```
[kilian@sh-114-03 ~]$ mdt-list-devices
Traceback (most recent call last):
  File "/share/software/user/open/py-mdt/0.10.8_py36/bin/mdt-list-devices", line 11, in <module>
    sys.exit(ListDevices.console_script())
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/mdt/shell_utils.py", line 44, in console_script
    cls().start(sys.argv[1:])
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/mdt/shell_utils.py", line 63, in start
    self.run(args, {})
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/mdt/cli_scripts/mdt_list_devices.py", line 28, in run
    for ind, env in enumerate(cl_environments.CLEnvironmentFactory.smart_device_selection()):
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 254, in smart_device_selection
    cl_environments = CLEnvironmentFactory.all_devices()
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 234, in all_devices
    env = CLEnvironment(platform, device)
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 23, in __init__
    self._context = cl.Context([device])
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
```

Some more info:
```
$ python3
Python 3.6.1 (default, Apr 27 2017, 10:57:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>> from mot.cl_environments import CLEnvironment
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> env = CLEnvironment(platform, device)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/mot/cl_environments.py", line 23, in __init__
    self._context = cl.Context([device])
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
>>> 
>>> import mot
>>> print(mot.__version__)
0.3.11
```

**Comment by robbert-harms** [comment]
This issue is getting more and more interesting. Could you try the following:

```
import pyopencl as cl

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]


class MockEnvironment(object):

    def __init__(self, platform, device):
        self._platform = platform
        self._device = device
        self._context = cl.Context([device])

environment = MockEnvironment(platform, device)
```

and if that works, try:

```
import pyopencl as cl
from mot.cl_environments import CLEnvironment

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]


class MockEnvironment(object):

    def __init__(self, platform, device):
        self._platform = platform
        self._device = device
        self._context = cl.Context([device])

environment = MockEnvironment(platform, device)
```
It might be a side effect of loading MOT. I am sorry the previous 'fix' did not work.

**Comment by kcgthb** [comment]
No worries at all, I appreciate your patience in fixing this :)

First test works:
```
$ python3
Python 3.6.1 (default, Apr 27 2017, 10:57:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>>
>>> class MockEnvironment(object):
...     def __init__(self, platform, device):
...         self._platform = platform
...         self._device = device
...         self._context = cl.Context([device])
...
>>> environment = MockEnvironment(platform, device)
```

But the second doesn't:
```
$ python3
Python 3.6.1 (default, Apr 27 2017, 10:57:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>> from mot.cl_environments import CLEnvironment
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> class MockEnvironment(object):
...     def __init__(self, platform, device):
...         self._platform = platform
...         self._device = device
...         self._context = cl.Context([device])
...
>>> environment = MockEnvironment(platform, device)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in __init__
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
```

**Comment by robbert-harms** [comment]
Of course, I want to fix this issue. It now seems that loading MOT has some side effects that causes the error. That would require some more tests. Could you try:

```
import pyopencl as cl
from mot.cl_environments import CLEnvironment

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
cl.Context([device])
```

If that fails, try:
```
import pyopencl as cl
import mot

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
cl.Context([device])
```
Hopefully that will tell us more.

**Comment by kcgthb** [comment]
Sure!
```
>>> import pyopencl as cl
>>> from mot.cl_environments import CLEnvironment
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> cl.Context([device])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
>>>
```

```
>>> import pyopencl as cl
>>> import mot
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> cl.Context([device])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
```

**Comment by robbert-harms** [comment]
Hi! This issue is quite a puzzle to me. I hope we can get to the bottom of this. Could you try this one now:

```
from mot.configuration import get_cl_environments
print(get_cl_environments())
```

I appreciate the (joint) effort!

Best, Robbert

**Comment by kcgthb** [comment]
No problem, here it is:
```
$ python3                                                                                                                                                                               
Python 3.6.1 (default, Apr 27 2017, 10:57:56)                                                                                                                                                               
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux                                                                                                                                                            
Type "help", "copyright", "credits" or "license" for more information.                                                                                                                                      
>>> import mot                                                                                                                                                                                              
>>> from mot.configuration import get_cl_environments
>>> print(get_cl_environments())                                                                                                                                                                            
[===========================================================================                                                                                                                                
<pyopencl.Platform 'NVIDIA CUDA' at 0x2364fb0>                                                                                                                                                              
===========================================================================                                                                                                                                 
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_i                                                                            nt32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device                                                                            _attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer                                                                                                                                    
name: NVIDIA CUDA                                                                                                                                                                                           
profile: FULL_PROFILE                                                                                                                                                                                       
vendor: NVIDIA Corporation                                                                                                                                                                                  
version: OpenCL 1.2 CUDA 9.1.84                                                                                                                                                                             
                                                                                                                                                                                                            
---------------------------------------------------------------------------                                                                                                                                 
<pyopencl.Device 'Tesla P100-SXM2-16GB' on 'NVIDIA CUDA' at 0x23b9dc0>                                                                                                                                      
---------------------------------------------------------------------------                                                                                                                                 
address bits: 64
attribute async engine count nv: 5
available: 1
available async queues amd: <error>
board name amd: <error>
built in kernels: 
compiler available: 1
compute capability major nv: 6
compute capability minor nv: 0
core temperature altera: <error>
double fp config: 63
driver version: 390.12
endian little: 1
error correction support: 1
execution capabilities: 1
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
ext mem padding in bytes qcom: <error>
gfxip major amd: <error>
gfxip minor amd: <error>
global free memory amd: <error>
global mem cacheline size: 128
global mem cache size: 917504
global mem cache type: 2
global mem channels amd: <error>
global mem channel banks amd: <error>
global mem channel bank width amd: <error>
global mem size: 17071734784
gpu overlap nv: 1
half fp config: <error>
host unified memory: 0
image2d max height: 32768
image2d max width: 16384
image3d max depth: 16384
image3d max height: 16384
image3d max width: 16384
image max array size: 2048
image max buffer size: 134217728
image support: 1
integrated memory nv: 0
kernel exec timeout nv: 0
linker available: 1
local mem banks amd: <error>
local mem size: 49152
local mem size per compute unit amd: <error>
local mem type: 1
max atomic counters ext: <error>
max clock frequency: 1480
max compute units: 56
max constant args: 9
max constant buffer size: 65536
max mem alloc size: 4267933696
max parameter size: 4352
max read image args: 256
max samplers: 32
max work group size: 1024
max work item dimensions: 3
max work item sizes: [1024, 1024, 64]
max write image args: 16
mem base addr align: 4096
me version intel: <error>
min data type align size: 128
name: Tesla P100-SXM2-16GB
native vector width char: 1
native vector width double: 1
native vector width float: 1
native vector width half: 0
native vector width int: 1
native vector width long: 1
native vector width short: 1
num simultaneous interops intel: <error>
opencl c version: OpenCL C 1.2 
page size qcom: <error>
PARENT_DEVICE: <error>
partition affinity domain: [0]
partition max sub devices: 1
partition properties: [0]
partition type: [0]
pci bus id nv: 4
pci slot id nv: 0
platform: <pyopencl.Platform 'NVIDIA CUDA' at 0x2364fb0>
preferred interop user sync: 0
preferred vector width char: 1
preferred vector width double: 1
preferred vector width float: 1
preferred vector width half: 0
preferred vector width int: 1
preferred vector width long: 1
preferred vector width short: 1
printf buffer size: <error>
profile: FULL_PROFILE
profiling timer offset amd: <error>
profiling timer resolution: 1000
queue properties: 3
reference count: 1
registers per block nv: 65536
simd instruction width amd: <error>
simd per compute unit amd: <error>
simd width amd: <error>
simultaneous interops intel: <error>
single fp config: 191
spir versions: <error>
thread trace supported amd: <error>
topology amd: <error>
type: 4
vendor: NVIDIA Corporation
vendor id: 4318
version: OpenCL 1.2 CUDA
warp size nv: 32
wavefront width amd: <error>

, ===========================================================================
<pyopencl.Platform 'NVIDIA CUDA' at 0x2364fb0>
===========================================================================
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
name: NVIDIA CUDA
profile: FULL_PROFILE
vendor: NVIDIA Corporation
version: OpenCL 1.2 CUDA 9.1.84

---------------------------------------------------------------------------
<pyopencl.Device 'Tesla P100-SXM2-16GB' on 'NVIDIA CUDA' at 0x21a24b0>
---------------------------------------------------------------------------
address bits: 64
attribute async engine count nv: 5
available: 1
available async queues amd: <error>
board name amd: <error>
built in kernels: 
compiler available: 1
compute capability major nv: 6
compute capability minor nv: 0
core temperature altera: <error>
double fp config: 63
driver version: 390.12
endian little: 1
error correction support: 1
execution capabilities: 1
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
ext mem padding in bytes qcom: <error>
gfxip major amd: <error>
gfxip minor amd: <error>
global free memory amd: <error>
global mem cacheline size: 128
global mem cache size: 917504
global mem cache type: 2
global mem channels amd: <error>
global mem channel banks amd: <error>
global mem channel bank width amd: <error>
global mem size: 17071734784
gpu overlap nv: 1
half fp config: <error>
host unified memory: 0
image2d max height: 32768
image2d max width: 16384
image3d max depth: 16384
image3d max height: 16384
image3d max width: 16384
image max array size: 2048
image max buffer size: 134217728
image support: 1
integrated memory nv: 0
kernel exec timeout nv: 0
linker available: 1
local mem banks amd: <error>
local mem size: 49152
local mem size per compute unit amd: <error>
local mem type: 1
max atomic counters ext: <error>
max clock frequency: 1480
max compute units: 56
max constant args: 9
max constant buffer size: 65536
max mem alloc size: 4267933696
max parameter size: 4352
max read image args: 256
max samplers: 32
max work group size: 1024
max work item dimensions: 3
max work item sizes: [1024, 1024, 64]
max write image args: 16
mem base addr align: 4096
me version intel: <error>
min data type align size: 128
name: Tesla P100-SXM2-16GB
native vector width char: 1
native vector width double: 1
native vector width float: 1
native vector width half: 0
native vector width int: 1
native vector width long: 1
native vector width short: 1
num simultaneous interops intel: <error>
opencl c version: OpenCL C 1.2
page size qcom: <error>
PARENT_DEVICE: <error>
partition affinity domain: [0]
partition max sub devices: 1
partition properties: [0]
partition type: [0]
pci bus id nv: 8
pci slot id nv: 0
platform: <pyopencl.Platform 'NVIDIA CUDA' at 0x2364fb0>
preferred interop user sync: 0
preferred vector width char: 1
preferred vector width double: 1
preferred vector width float: 1
preferred vector width half: 0
preferred vector width int: 1
preferred vector width long: 1
preferred vector width short: 1
printf buffer size: <error>
profile: FULL_PROFILE
profiling timer offset amd: <error>
profiling timer resolution: 1000
queue properties: 3
reference count: 1
registers per block nv: 65536
simd instruction width amd: <error>
simd per compute unit amd: <error>
simd width amd: <error>
simultaneous interops intel: <error>
single fp config: 191
spir versions: <error>
thread trace supported amd: <error>
topology amd: <error>
type: 4
vendor: NVIDIA Corporation
vendor id: 4318
version: OpenCL 1.2 CUDA
warp size nv: 32
wavefront width amd: <error>

]
>>>
```

**Comment by robbert-harms** [comment]
and does any of these two crash?

```
import pyopencl as cl
from mot.configuration import get_cl_environments
get_cl_environments()
```

```
import pyopencl as cl

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
context = cl.Context([device])

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
context = cl.Context([device])
```

**Comment by kcgthb** [comment]
The first one works:
```
$ python3
Python 3.6.1 (default, Apr 27 2017, 10:57:56) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>> from mot.configuration import get_cl_environments
>>> get_cl_environments()
[===========================================================================
<pyopencl.Platform 'NVIDIA CUDA' at 0x182ed90>
===========================================================================
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
name: NVIDIA CUDA
profile: FULL_PROFILE
vendor: NVIDIA Corporation
version: OpenCL 1.2 CUDA 9.1.84

---------------------------------------------------------------------------
<pyopencl.Device 'Tesla P100-SXM2-16GB' on 'NVIDIA CUDA' at 0x1778400>
---------------------------------------------------------------------------
address bits: 64
attribute async engine count nv: 5
available: 1
available async queues amd: <error>
board name amd: <error>
built in kernels: 
compiler available: 1
compute capability major nv: 6
compute capability minor nv: 0
core temperature altera: <error>
double fp config: 63
driver version: 390.12
endian little: 1
error correction support: 1
execution capabilities: 1
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
ext mem padding in bytes qcom: <error>
gfxip major amd: <error>
gfxip minor amd: <error>
global free memory amd: <error>
global mem cacheline size: 128
global mem cache size: 917504
global mem cache type: 2
global mem channels amd: <error>
global mem channel banks amd: <error>
global mem channel bank width amd: <error>
global mem size: 17071734784
gpu overlap nv: 1
half fp config: <error>
host unified memory: 0
image2d max height: 32768
image2d max width: 16384
image3d max depth: 16384
image3d max height: 16384
image3d max width: 16384
image max array size: 2048
image max buffer size: 134217728
image support: 1
integrated memory nv: 0
kernel exec timeout nv: 0
linker available: 1
local mem banks amd: <error>
local mem size: 49152
local mem size per compute unit amd: <error>
local mem type: 1
max atomic counters ext: <error>
max clock frequency: 1480
max compute units: 56
max constant args: 9
max constant buffer size: 65536
max mem alloc size: 4267933696
max parameter size: 4352
max read image args: 256
max samplers: 32
max work group size: 1024
max work item dimensions: 3
max work item sizes: [1024, 1024, 64]
max write image args: 16
mem base addr align: 4096
me version intel: <error>
min data type align size: 128
name: Tesla P100-SXM2-16GB
native vector width char: 1
native vector width double: 1
native vector width float: 1
native vector width half: 0
native vector width int: 1
native vector width long: 1
native vector width short: 1
num simultaneous interops intel: <error>
opencl c version: OpenCL C 1.2 
page size qcom: <error>
PARENT_DEVICE: <error>
partition affinity domain: [0]
partition max sub devices: 1
partition properties: [0]
partition type: [0]
pci bus id nv: 4
pci slot id nv: 0
platform: <pyopencl.Platform 'NVIDIA CUDA' at 0x182ed90>
preferred interop user sync: 0
preferred vector width char: 1
preferred vector width double: 1
preferred vector width float: 1
preferred vector width half: 0
preferred vector width int: 1
preferred vector width long: 1
preferred vector width short: 1
printf buffer size: <error>
profile: FULL_PROFILE
profiling timer offset amd: <error>
profiling timer resolution: 1000
queue properties: 3
reference count: 1
registers per block nv: 65536
simd instruction width amd: <error>
simd per compute unit amd: <error>
simd width amd: <error>
simultaneous interops intel: <error>
single fp config: 191
spir versions: <error>
thread trace supported amd: <error>
topology amd: <error>
type: 4
vendor: NVIDIA Corporation
vendor id: 4318
version: OpenCL 1.2 CUDA
warp size nv: 32
wavefront width amd: <error>

, ===========================================================================
<pyopencl.Platform 'NVIDIA CUDA' at 0x182ed90>
===========================================================================
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
name: NVIDIA CUDA
profile: FULL_PROFILE
vendor: NVIDIA Corporation
version: OpenCL 1.2 CUDA 9.1.84

---------------------------------------------------------------------------
<pyopencl.Device 'Tesla P100-SXM2-16GB' on 'NVIDIA CUDA' at 0x11f5130>
---------------------------------------------------------------------------
address bits: 64
attribute async engine count nv: 5
available: 1
available async queues amd: <error>
board name amd: <error>
built in kernels: 
compiler available: 1
compute capability major nv: 6
compute capability minor nv: 0
core temperature altera: <error>
double fp config: 63
driver version: 390.12
endian little: 1
error correction support: 1
execution capabilities: 1
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
ext mem padding in bytes qcom: <error>
gfxip major amd: <error>
gfxip minor amd: <error>
global free memory amd: <error>
global mem cacheline size: 128
global mem cache size: 917504
global mem cache type: 2
global mem channels amd: <error>
global mem channel banks amd: <error>
global mem channel bank width amd: <error>
global mem size: 17071734784
gpu overlap nv: 1
half fp config: <error>
host unified memory: 0
image2d max height: 32768
image2d max width: 16384
image3d max depth: 16384
image3d max height: 16384
image3d max width: 16384
image max array size: 2048
image max buffer size: 134217728
image support: 1
integrated memory nv: 0
kernel exec timeout nv: 0
linker available: 1
local mem banks amd: <error>
local mem size: 49152
local mem size per compute unit amd: <error>
local mem type: 1
max atomic counters ext: <error>
max clock frequency: 1480
max compute units: 56
max constant args: 9
max constant buffer size: 65536
max mem alloc size: 4267933696
max parameter size: 4352
max read image args: 256
max samplers: 32
max work group size: 1024
max work item dimensions: 3
max work item sizes: [1024, 1024, 64]
max write image args: 16
mem base addr align: 4096
me version intel: <error>
min data type align size: 128
name: Tesla P100-SXM2-16GB
native vector width char: 1
native vector width double: 1
native vector width float: 1
native vector width half: 0
native vector width int: 1
native vector width long: 1
native vector width short: 1
num simultaneous interops intel: <error>
opencl c version: OpenCL C 1.2
page size qcom: <error>
PARENT_DEVICE: <error>
partition affinity domain: [0]
partition max sub devices: 1
partition properties: [0]
partition type: [0]
pci bus id nv: 8
pci slot id nv: 0
platform: <pyopencl.Platform 'NVIDIA CUDA' at 0x182ed90>
preferred interop user sync: 0
preferred vector width char: 1
preferred vector width double: 1
preferred vector width float: 1
preferred vector width half: 0
preferred vector width int: 1
preferred vector width long: 1
preferred vector width short: 1
printf buffer size: <error>
profile: FULL_PROFILE
profiling timer offset amd: <error>
profiling timer resolution: 1000
queue properties: 3
reference count: 1
registers per block nv: 65536
simd instruction width amd: <error>
simd per compute unit amd: <error>
simd width amd: <error>
simultaneous interops intel: <error>
single fp config: 191
spir versions: <error>
thread trace supported amd: <error>
topology amd: <error>
type: 4
vendor: NVIDIA Corporation
vendor id: 4318
version: OpenCL 1.2 CUDA
warp size nv: 32
wavefront width amd: <error>

]
>>>
```

The second one doesn't:
```
$ python3
Python 3.6.1 (default, Apr 27 2017, 10:57:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> context = cl.Context([device])
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> context = cl.Context([device])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 811, in __init__
    num_devices, _devices))
  File "/share/software/user/open/py-mdt/0.10.8_py36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 664, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clCreateContext failed: INVALID_DEVICE
```

**Comment by robbert-harms** [comment]
Ah, but than we have found the issue. As you can see, in the last test we did not import MOT/MDT, only PyOpenCL. The problem seems to be that PyOpenCL crashes when you try to create a second context for the same device.

In the end it is then more of a PyOpenCL bug than a MOT bug, but I can try to store and reuse CL contexts to try to circumvent the issue. Could you try to see if this would work:

```
import pyopencl as cl

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
context = cl.Context([device])

del context

platform = cl.get_platforms()[0]
device = platform.get_devices()[0]
context = cl.Context([device])
```

**Comment by kcgthb** [comment]
Interesting, indeed!
Yes, that works:
```
$ python3
Python 3.6.1 (default, Apr 27 2017, 10:57:56)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> context = cl.Context([device])
>>>
>>> del context
>>>
>>> platform = cl.get_platforms()[0]
>>> device = platform.get_devices()[0]
>>> context = cl.Context([device])
>>>
```

**Comment by robbert-harms** [comment]
Alright, I'll need to think about a possible work around for this. I think I can keep track of existing contexts and reuse them. I'll let you know!

**Comment by kcgthb** [comment]
Excellent, thanks!

**Comment by robbert-harms** [comment]
Hi Kilian, 

I asked your question on the PyOpenCL issue tracker as well, and Andreas said the fix might be a setting in the NVIDIA driver:

> If they have the (Nvidia I'm guessing) compute device set to "exclusive" (or some such, I forget the terminology) mode (using nvidia-smi), then it would only allow creation of a single context.

(https://github.com/inducer/pyopencl/issues/223#issuecomment-367739841)

If changing that setting is an option than that would be way easier. Also perhaps better for future compatibility with other OpenCL software. 

Best,

Robbert

**Comment by robbert-harms** [comment]
From one of the manuals (https://developer.download.nvidia.com/compute/DCGM/docs/nvidia-smi-367.38.pdf)

>   -c, --compute-mode=MODE
       Set  the  compute  mode  for the target GPUs.  See the (GPU ATTRIBUTES)
       section for a description of compute mode.  Requires root.  Will impact
       all  GPUs  unless a single GPU is specified using the -i argument.  The
       effect of this operation is immediate.  However, it  does  not  persist
       across   reboots.   After  each  reboot  compute  mode  will  reset  to
       "DEFAULT".

>    Compute Mode
       The compute mode flag indicates whether individual or multiple  compute applications may run on the GPU.
       "Default" means multiple contexts are allowed per device.
       "Exclusive  Process"  means  only  one  context  is allowed per device, usable from multiple threads at a time.
       "Prohibited" means no contexts  are  allowed per  device  (no  compute apps).

you can probably use `nvidia-smi -c Default` to set the setting back to default.

**Comment by kcgthb** [comment]
Hi Robbert,

Ah, that's an excellent point: we do indeed set our GPUs in Exclusive process mode, to prevent our users from stepping on each other's toes. I can confirm that setting GPUs back to the default (shared) mode allows `mdt-list-devices` to properly enumerate devices:
```
$ mdt-list-devices
Device 0:
GPU - Tesla P100-SXM2-16GB (NVIDIA CUDA)
Device 1:
GPU - Tesla P100-SXM2-16GB (NVIDIA CUDA)
```

Does MDT requires the creation of multiple processes/contexts? If that's the case, then we'll let our users know about it, and recommend them to change the mode before running MDT. We found that putting GPUs in Exclusive mode avoided a lot of user mistakes and generally provided better and more consistent performance across runs, so if that's an option to make MDT use a single context, that would make the software more robust with regard to different environments.

Thanks for helping navigating this issue, that's much appreciated!

**Comment by robbert-harms** [comment]
Well, essentially, no, it would not. A single context suffices, it probably makes MDT a little bit faster as well. 

I can probably now reproduce the issue on one of my machines with an Nvidia card by changing the compute mode. With that I can work towards a solution.

**Comment by robbert-harms** [comment]
Hi Kilian,

I managed to reproduce the issue on my nvidia machine and I managed to make a patch with a solution. 

Could you try updating MDT to version 0.10.9 and MOT to version 0.3.12 (latest versions) and see if this will work for you as well?

Best,

Robbert

**Comment by kcgthb** [comment]
Version 0.10.9 works in both Exclusive and Default mode, that's perfect!
Thanks so much for all your help.

**Comment by robbert-harms** [comment]
Thank you, for your contribution!

If there is anything else, do let me know.

Best,

Robbert
